# docker-compose.yml (Updated for MongoDB Atlas)
services:
  # Backend API (No local MongoDB needed - using Atlas)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    container_name: lms_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb+srv://kieuphuchuy2002:kieuhuy123@cluster0.ry9hyye.mongodb.net/teen-up?retryWrites=true&w=majority&appName=Cluster0
      - CLIENT_URL=http://localhost:5173
      - maxPool=10
      - serverSelection=5000
    networks:
      - lms_network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
      args:
        - VITE_API_URL=http://localhost:5000
    container_name: lms_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - lms_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Define network
networks:
  lms_network:
    driver: bridge

---

# docker-compose.override.yml (Updated for development)
services:
  # Development overrides for backend only
  backend:
    environment:
      - NODE_ENV=development
      - DEBUG=lms:*
      - PORT=5000
      - MONGODB_URI=mongodb+srv://kieuphuchuy2002:kieuhuy123@cluster0.ry9hyye.mongodb.net/teen-up?retryWrites=true&w=majority&appName=Cluster0
      - CLIENT_URL=http://localhost:5173
      - maxPool=10
      - serverSelection=5000
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - "5000:5000"

  # Keep frontend in production mode to avoid Vite issues in Docker
  frontend:
    environment:
      - VITE_API_URL=http://localhost:5000
    ports:
      - "5173:5173"