services:
  # Development overrides for backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    environment:
      - NODE_ENV=development
      - DEBUG=lms:*
      - PORT=5000
      - MONGODB_URI=mongodb+srv://kieuphuchuy2002:kieuhuy123@cluster0.ry9hyye.mongodb.net/teen-up?retryWrites=true&w=majority&appName=Cluster0
      - CLIENT_URL=http://localhost:5173
      - maxPool=10
      - serverSelection=5000
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  # Development overrides for frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: builder
    environment:
      - VITE_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "5173:5173"